apiVersion: v2
name: jenkins-custom
description: A Helm chart for deploying Jenkins with a custom image
version: 5.7.8

dependencies:
  - name: jenkins
    version: "5.7.8"
    repository: "https://charts.jenkins.io"