apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
spec:
  containers:
    - name: dast
      image: fadifarid/redhat-python
      command: ["sh", "-c", "sleep infinity"]
      tty: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent

    - name: sast
      image: golang:1.23-bookworm
      tty: true
      command:
        - cat
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
    - name: buildpy
      image: python:3.10
      tty: true
      command:
        - cat
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
    - name: trivy
      image: aquasec/trivy:canary
      tty: true
      command:
        - cat
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command: ["/busybox/sleep", "infinity"]
      tty: true
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/
        - mountPath: /workspace
          name: workspace-volume

  restartPolicy: Never
  volumes:
    - name: workspace-volume
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
        items:
        - key: .dockerconfigjson  
          path: config.json       
 

